Add comments and help message

diff --git a/templates/mount_vm.sh.j2 b/templates/mount_vm.sh.j2
--- a/templates/mount_vm.sh.j2
+++ b/templates/mount_vm.sh.j2
@@ -1,19 +1,39 @@
 #!/bin/bash
 # {{ ansible_managed }}
+#
+# mounts or umounts the root filesystem from the given vm
+#
+# command line arguments:
+#   -m|--mount                           mount the given vm
+#   -u|--umount                          umounts given vm
+#   -s|--systemd    <vm-org>-<vm-host>   specifies the vm
+#   -o|--org        <vm-org>             specifies the vm organisation
+#   -h|--host       <vm-host>            specifies the vm host
+#   -p|--mount_path <mount path>         specifies where to mount, defaults to /mnt/vms/<vm-org>-<vm-host>
+#
+# at least one of -m or -u must be given
+# either both of -o and -h or -s must be given
 
 function mount_iscsi() {
 	local blk_dev="/dev/disk/by-path/ip-{{ xen_vman_iscsi_server }}-iscsi-{{ xen_vman_iscsi_base_wwn }}:$vm-lun-0"
+
 	# login into iscsi for requested vm, needed for standalone starts(via script), do not so if started via systemd
 	[ ! -b "$blk_dev" -a -z "$INVOCATION_ID" ] && {
 		touch /tmp/.$vm.iscsi_started_by_mount_script
 		systemctl start vm_iscsi@$vm.service
-  	}
+	}
+
+	# wait for block device
 	timeout=$(({{ xen_vman_iscsi_login_timeout }}*2))
-	while [ ! -b "$blk_dev" ]; do  # wait for block device
+	while [ ! -b "$blk_dev" ]; do
 	  sleep 0.5
 	  timeout=$((timeout-1))
 	done
-	[ "$timeout" -le 0 ] && { echo "ERROR:   Iscsi login has reached timeout"; exit 1; }
+
+	[ "$timeout" -le 0 ] && {
+		echo "ERROR:   Iscsi login has reached timeout"
+		exit 1
+	}
 	mount -v -o "defaults,rw" "$blk_dev" "$mount_path"
 }
 
@@ -24,6 +44,7 @@ function mount_nfs() {
 function detect_storage_type() {
 	sed -n 's/# storage type:[ ]\+//p' "$config_path"
 }
+
 
 # Parse arguments
 while [[ $# -gt 0 ]]; do
@@ -46,6 +67,9 @@ while [[ $# -gt 0 ]]; do
 		"-p" | "--mount_path")
 			shift; mount_path="$1"
 			;;
+		"-?" | "--help")
+			head -n 15 $0 | tail -n 10
+			;;
 		*)
 			echo "WARNING: Unknown option '$1'"
 			;;
@@ -53,17 +77,21 @@ while [[ $# -gt 0 ]]; do
 	shift
 done
 
+
 config_path="{{ xen_vman_vm_config_path }}/$vm.cfg"
 
-[ -n "$org" -a -n "$host" ]        &&   vm="$org-$host"  # vm is specified by org and host
+# Check for all arguments and exit if something is missing
+[ -n "$org" -a -n "$host" ]        && vm="$org-$host"  # vm is specified by org and host
 [ -z "$vm" ]                       && { echo "ERROR:   No vm specified"; exit 1; }  # Exit if no vm is specified
 [ -f "$config_path" ]              || { echo "ERROR:   Invalid vm specified ($vm)"; exit 1; }  # Exit if vm is not found
 [ -z "$action" ]                   && { echo "ERROR:   Exactly one of \"-m\" or \"-u\" must be specified"; exit 1; }
 systemctl is-active vm@$vm.service && { echo "ERROR:   Can't mount running vm ($vm)"; exit 1; }
 
-: ${mount_path:=/mnt/vms/$vm}
 
+# Set the default mount path if not specified and create them
+: ${mount_path:=/mnt/vms/$vm}
 mkdir -pv "$mount_path"
+
 
 err=0
 case "$action $(detect_storage_type)" in
@@ -71,10 +99,12 @@ case "$action $(detect_storage_type)" in
 		mount_nfs && exit 0 || err=$?
 		echo "ERROR:   Failed to mount nfs storage for '$vm'"
 		;;
+
 	"mount iscsi")
 		mount_iscsi && exit 0 || err=$?
 		echo "ERROR:   Failed to mount iscsi storage for '$vm'"
 		;;
+
 	"umount iscsi" |\
 	"umount nfs")
 		umount "$mount_path" || err=$?
@@ -84,8 +114,10 @@ case "$action $(detect_storage_type)" in
 		}
 		rmdir "$mount_path"
 		;;
+
 	*)
 		echo "ERROR:   Invalid storage backend type ($(detect_storage_type))"; err=1
 		;;
+
 esac
 exit $err
